name: datafusion-infra
runtime: nodejs
description: GKE Autopilot infrastructure for DataFusion benchmarking
config:
  gcp:project:
    value: datafusion-benchmarking
  gcp:region:
    value: us-central1
