name: datafusion-infra
runtime: nodejs
description: GKE Autopilot infrastructure for DataFusion benchmarking
config:
  gcp:project:
    description: GCP project ID
    value: datafusion-benchmarking
  gcp:region:
    default: us-central1
    value: us-central1
